spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/querydsl
    username: study
    password : pass
    driver-class-name: org.postgresql.Driver



logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace