spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/querydsl
    username: study
    password : pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace